
#网站设置 详细https://github.com/mojombo/jekyll/wiki/configuration
markdown:         rdiscount
pygments:         true
paginate:         4
#permalink: /:year/:month/:day/:title
permalink:        /post/:title.html

title:            Joyuan
url:              
prod_url:         http://qianzhaoyuan.com
feed:             atom.xml
author:
    name:         Joyuan
    email:        qianzhaoyuan@gmail.com

follow:
    email:        qianzhaoyuan@gmail.com
    github:       https://github.com/Joyuan
    twitter:      https://www.twitter.com/qianzhaoyuan
    google:       https://plus.google.com/
    facebook:     https://facebook.com/qianzhaoyuan
    weibo:     	  http://weibo.com/qianzhaoyuan


indexContent:     true


keywords:         "Joyuan, Joyuan个人博客"
description:      "Henter's personal site, focus on the web."

blogName:         Joyuan
blogDesc:         自我介绍
favicon:          favicon.ico
theme:            henter-diandian

disqus:           henter

copyright:        Copyright © 2008-2013 Henter All rights reserved.

music:            http://a.libdd.com/farm1/19/53EAEE74712880DBF40B0A7915561C13.mp3
